create table bills
(
    bill_id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url         varchar                          not null unique,
    bill_number bigint check ( bill_number > 0 ) not null,
    bill_date   date                             not null,
    customer    varchar(100)                     not null,
    route       varchar(100)                     not null,
    cost        integer check ( cost > 0 )       not null,
    created_at  timestamp                        not null
);

